"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const validationModule_1 = require("./module/validationModule");
exports.ValidationModule = validationModule_1.ValidationModule;
const validateDecorator_1 = require("./module/src/decorators/validateDecorator");
exports.validate = validateDecorator_1.validate;
const appolo_validator_1 = require("appolo-validator");
exports.boolean = appolo_validator_1.boolean;
exports.object = appolo_validator_1.object;
exports.number = appolo_validator_1.number;
exports.array = appolo_validator_1.array;
exports.string = appolo_validator_1.string;
exports.buffer = appolo_validator_1.buffer;
exports.date = appolo_validator_1.date;
exports.when = appolo_validator_1.when;
exports.any = appolo_validator_1.any;
exports.or = appolo_validator_1.or;
exports.ref = appolo_validator_1.ref;
exports.func = appolo_validator_1.func;
exports.and = appolo_validator_1.and;
//# sourceMappingURL=index.js.map