"use strict";
import {ValidationModule} from "./module/validationModule";
import {
    validate,
    validateModel,
    validateBody,
    validateParams,
    validateQuery
} from "./module/src/decorators/validateDecorator"
import {IOptions} from "./module/src/IOptions"

import {
    string,
    object,
    number,
    registerConverter,
    array,
    boolean,
    schema,
    registerSchema,
    and,
    buffer,
    date,
    when,
    any,
    or,
    ref,
    func,
    IConstraint,
    IConverter,
    StringSchema,
    AnySchema,
    ArraySchema,
    BooleanSchema,
    NumberSchema,
    ObjectSchema,
    FunctionSchema,
    BufferSchema,
    DateSchema,
    ValidationParams, Validator,
    IConstraintValidateResult, registerConstraint
} from "appolo-validator"

export {
    ValidationModule,
    validate,
    IOptions,
    string,
    object,
    number,
    registerConverter,
    registerConstraint,
    array,
    boolean,
    schema,
    registerSchema,
    and,
    buffer,
    date,
    when,
    any,
    or,
    ref,
    func,
    IConstraint,
    IConverter,
    StringSchema,
    AnySchema,
    ArraySchema,
    BooleanSchema,
    NumberSchema,
    ObjectSchema,
    FunctionSchema,
    BufferSchema,
    DateSchema,
    ValidationParams,
    IConstraintValidateResult, Validator, validateModel,validateBody,
    validateParams,
    validateQuery
}

