"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.func = exports.ref = exports.or = exports.any = exports.when = exports.date = exports.buffer = exports.and = exports.registerSchema = exports.schema = exports.boolean = exports.array = exports.registerConverter = exports.number = exports.object = exports.string = exports.validate = exports.ValidationModule = void 0;
const validationModule_1 = require("./module/validationModule");
Object.defineProperty(exports, "ValidationModule", { enumerable: true, get: function () { return validationModule_1.ValidationModule; } });
const validateDecorator_1 = require("./module/src/decorators/validateDecorator");
Object.defineProperty(exports, "validate", { enumerable: true, get: function () { return validateDecorator_1.validate; } });
const appolo_validator_1 = require("appolo-validator");
Object.defineProperty(exports, "string", { enumerable: true, get: function () { return appolo_validator_1.string; } });
Object.defineProperty(exports, "object", { enumerable: true, get: function () { return appolo_validator_1.object; } });
Object.defineProperty(exports, "number", { enumerable: true, get: function () { return appolo_validator_1.number; } });
Object.defineProperty(exports, "registerConverter", { enumerable: true, get: function () { return appolo_validator_1.registerConverter; } });
Object.defineProperty(exports, "array", { enumerable: true, get: function () { return appolo_validator_1.array; } });
Object.defineProperty(exports, "boolean", { enumerable: true, get: function () { return appolo_validator_1.boolean; } });
Object.defineProperty(exports, "schema", { enumerable: true, get: function () { return appolo_validator_1.schema; } });
Object.defineProperty(exports, "registerSchema", { enumerable: true, get: function () { return appolo_validator_1.registerSchema; } });
Object.defineProperty(exports, "and", { enumerable: true, get: function () { return appolo_validator_1.and; } });
Object.defineProperty(exports, "buffer", { enumerable: true, get: function () { return appolo_validator_1.buffer; } });
Object.defineProperty(exports, "date", { enumerable: true, get: function () { return appolo_validator_1.date; } });
Object.defineProperty(exports, "when", { enumerable: true, get: function () { return appolo_validator_1.when; } });
Object.defineProperty(exports, "any", { enumerable: true, get: function () { return appolo_validator_1.any; } });
Object.defineProperty(exports, "or", { enumerable: true, get: function () { return appolo_validator_1.or; } });
Object.defineProperty(exports, "ref", { enumerable: true, get: function () { return appolo_validator_1.ref; } });
Object.defineProperty(exports, "func", { enumerable: true, get: function () { return appolo_validator_1.func; } });
//# sourceMappingURL=index.js.map